### ISSUE TITLE
Create command line tool interface

### ISSUE THREAD

**Issue by vogelino** [vogelino/extendscriptr#10]
with parameters like:
- pathToScript
- outputPath
- (includeBasilJs)

@fabiantheblind Any idea how to do this? Never done this before.

**Comment by fabiantheblind** [comment]
we could use something like [vorpal](https://www.npmjs.com/package/vorpal) or [commander](https://www.npmjs.com/package/commander)

**Comment by fabiantheblind** [comment]
I already used commander. But from the blogosphere vorpal sounds like the hot stuff currently

**Comment by vogelino** [comment]
Also interesting: https://developer.atlassian.com/blog/2015/11/scripting-with-node/
