### ISSUE TITLE
Will #target "InDesign" break the compilation?

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/extendscriptr#13]
see also #12   

    #target "InDesign"

in line 41 throws an error.

**Comment by vogelino** [comment]
Lines starting with `#` shouldn't be present in the code.
For things like `#include`, we should replace them with `import` and bundle the file.
For things like `#target`, that I assume, will appear once on top of the file, we could add relevant flags in the command line interface we will provide in the future.

**Example:**
``
	extendscriptr -s myScript.js -o myOutput.js --target 'InDesign'
``

**Comment by fabiantheblind** [comment]
Yes that would be awesome. I think having the `#target 'InDesign'` should not be a problem. I just ran a test directly from node. So the error came from that. If executed in ExtendScript  it should work.
