### ISSUE TITLE
needs a snappy name (before publishing it to the registry)

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/extendscriptr#14]
- [ ] brass monkey?
- [ ] Extendscript6?   
- [ ] super mumbo jumbo?  
- [ ] something totally different

**Comment by vogelino** [comment]
what about badassjs ? :P

**Comment by fabiantheblind** [comment]
Don't know but the current title is pretty long to type. :)

**Comment by fabiantheblind** [comment]
Btw. http://badassjs.com Is already taken ;)

**Comment by vogelino** [comment]
The name was changed to extendsciptr as an utility to turn javascript into executable extendscripts
