### ISSUE TITLE
error running test script defineProperty is undefined 

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/extendscriptr#18]
When I run the test script in ID I get an error that defineProperty is undefined. I think the polyfill for it needs to be included in the bundled script before anything else. 
I'll make a test later on or tomorrow.

**Comment by vogelino** [comment]
Okay wierd because I explicitly prepend it on top of the file. What script are you executing? 
Try to run `npm start` and to execute `dist/output.js`. I got a different error than you have. Instead, a popup opens and tells that The script cannot be executed in main. Don't ask me what it means. I don't have a clue. :/

**Comment by fabiantheblind** [comment]
I'll test it ASAP

**Comment by vogelino** [comment]
The `Object.defineProperty`polyfill is successfully inserted on top of the bundle, before everything. Still, it seem to be undefined anyway. I'll have a closer look at it.

**Comment by fabiantheblind** [comment]
![error-in-id](https://cloud.githubusercontent.com/assets/315106/14911704/60d55dc0-0df7-11e6-9600-f4eb47a2e5c4.png)

the error is the same.

**Comment by vogelino** [comment]
Yeah, that's why I closed it as a duplicated. :)

**Comment by vogelino** [comment]
Actually, if `Object.defineProperty` was undefined the error should be `undefined is not a function` right?

**Comment by fabiantheblind** [comment]
I think the problem is bigger the we thought see #20 #19 one solution would be having a own polyfill repo like I started here https://github.com/fabiantheblind/extendscript.prototypes

**Comment by fabiantheblind** [comment]
So we can add piece by piece what we need. Just including everything that is meant for browsers won't work

**Comment by fabiantheblind** [comment]
Btw this error here only occurs with the babel-polyfill not with es5-shim

**Comment by vogelino** [comment]
As we now changed our philosophy and don't insert whole polyfill implementations originally intended for browser use, I close this issues.
