### ISSUE TITLE
what about the the #include statements

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/extendscriptr#6]
Does it still work if there is a `#include` in a sub file?

**Comment by vogelino** [comment]
No it doesn't. See my comment on https://github.com/basiljs/basil.js/pull/31#issuecomment-215041645

**Comment by fabiantheblind** [comment]
Okay. Maybe we should not burden the basil authors with that. If we can come up with a simple build process for basil within our module this should be enough. Later on we can make a PR with a compiled version.

**Comment by vogelino** [comment]
Yeah you're right. I never meant to burden them with that but rather wanted to start a discussion. I don't expect them to create a perfect npm module just for us in time. Would be great though. 😄

**Comment by fabiantheblind** [comment]
Yeah. it would. I know Benedikt is pretty busy. What I don't know is how much Basil is still in use by Ludwig at Academy of Art and Design Basel. Anyway. We can still do a full build process from my fork and use mine in the module until we think it is worth it to do another PR.

**Comment by vogelino** [comment]
Yes, let's do it so. If they like your fork, they still could merge it later on. 👍
